# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      # Linting
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/xml-lint.yml
      # CI
      - /gitlab-templates/linux.yml
      # The FreeBSD is not containerized and hence has Qt5 and Qt6 around
      # Kdenlive preferes Qt6 and there is no way to tell the CI to use Qt5 in this case
      #- /gitlab-templates/freebsd.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      # CD Qt5
      #- /gitlab-templates/craft-appimage.yml
      #- /gitlab-templates/craft-windows-mingw64.yml
      #- /gitlab-templates/craft-macos-x86-64.yml
      #- /gitlab-templates/craft-macos-arm64.yml
      # CD Qt6
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/craft-appimage-qt6.yml
      - /gitlab-templates/craft-windows-mingw64-qt6.yml
      - /gitlab-templates/craft-macos-x86-64-qt6.yml
      - /gitlab-templates/craft-macos-arm64-qt6.yml
  